---
services:
  cloudflared:
    image: ghcr.io/miladiir/cloudflared-wget:latest
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    restart: unless-stopped