---
services:
  cloudflared:
    image: ghcr.io/miladiir/cloudflared-wget:latest
    environment:
      - TUNNEL_METRICS=127.0.0.1:2000
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    healthcheck:
      test: ["CMD", "/bin/docker-healthcheck.sh"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 5s
    command: tunnel --no-autoupdate run
    restart: unless-stopped